### ISSUE TITLE
Not work with `mdbook v0.4.28`

### ISSUE THREAD

**Issue by gnu4cn** [badboy/mdbook-last-changed#4]
Here is the error message.

```console
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/unisko/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbook-last-changed-0.1.2/src/lib.rs:18:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-04-08 12:59:37 [ERROR] (mdbook::utils): Error: The "last-changed" preprocessor exited unsuccessfully with exit status: 101 status
```

**Comment by gnu4cn** [comment]
Maybe it's caused by the use of sapling-scm of my book instead of the git-scm. So please add sapling-scm support.

**Comment by badboy** [comment]
I have no idea what sapling is, but yeah, if you don't use git this tool won't work and I have no intention of adding support for something else.

(I should make the error nicer though)

**Comment by gnu4cn** [comment]
@badboy , Ok, please have a look at [https://sapling-scm.com/](https://sapling-scm.com/)

**Comment by badboy** [comment]
> @badboy , Ok, please have a look at [sapling-scm.com](https://sapling-scm.com/)

Ah, that sapling. Yeah, I still don't have any intention to support it here.
