### ISSUE TITLE
Date/commit always last commit on gh-pages

### ISSUE THREAD

**Issue by dvogt23** [badboy/mdbook-last-changed#9]
Hey thanks for this pre-processor @badboy 🙏🏾 

I got this issue, always showing last commit and that date. Locally it works, but after deploy to gh-pages: 

https://notes.vogt.dev/tech/app/firefox.html

Any ideas whats wrong?

**Comment by badboy** [comment]
`action/checkout` only fetches the latest commit by default:

```
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +069eb61c319f043c8091a51cae021ba82cf8d60a:refs/remotes/origin/main
```

So of course then `mdbook-last-changed` is trying to look up git information it only finds a single commit: the latest.

Change your action to fetch the whole history, see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
